### ISSUE TITLE
Looking for help on decoupling timestamp/userlist coloring

### ISSUE THREAD

**Issue by ghost** [SoniEx2/torxchat#4]
Hi, I'm trying to `dim` the colors of both the `timestamp` and `userlist`. Ideally these could be set separately, but I'd be happy with patching hexchat locally too. Getting nowhere (yet), still familiarizing with the codebase.

I'd appreciate any pointers people might have regarding where to start looking.

Cheers for offering this fork,

Regards

**Comment by SoniEx2** [comment]
Hello! Uh, sorry, what is `dim`?

**Comment by ghost** [comment]
Hi. I should have described that better. I use a somewhat darkish background for hexchat in combination with a brighter text color (to blend in hexchat with the look of some other GTK2 apps in use).

Settings > Preferences > Interface > Text Colors:
foreground color: #A4A4A4
background color: #252A2B
Userlist set to follow the text-color settings

With `dim` I mean that I'd like to give the timestamp and userlist items a somewhat darker color, so the actual IRC messages (what - hopefully actual - people communicate) obtain more focus than the IRC metadata (like the timestamp and the present users). It also would have been more informative if I added that I'm blessed with braincells that seem to prefer uncluttered GUI's ;-)

Hope this can help clearing things up.

**Comment by SoniEx2** [comment]
Right. Hexchat's GUI is by far one of the most miserable legacy parts of the entire thing. You may want to look for uses of the `colors` array, defined in `palette.h`? This might point you to being able to adjust the userlist.

However, for the timestamp, it's far simpler, you can just input color codes into the `Timestamp` field in `Settings` > `Preferences` > `Interface` > `Appearance`, like so:

![Setting the timestamp to have custom formatting](https://github.com/SoniEx2/sonis-fork-of-hexchat/assets/1779619/8a6257c6-6a80-4ec2-882c-bbb265c7a481)

(In order to type the special formatting codes, you can use the key combination ctrl+shift+u to enter codepoint input mode, and end it with a space. To set the color use U+0003 (enter unicode input mode, type 3, then type space) and remember to reset formatting with U+000F (likewise, but with f instead of 3) after the timestamp so it doesn't overflow into the message.)

**Comment by ghost** [comment]
I'll start with trying to get the timestamps sorted. Never realized that the format could include formatting codes to that effect. A big thank you for pointing that out in detail.

The userlist is for later. The palette.h pointer and colors array are a start, that was what I was looking for.

Thank you kindly for taking the time to respond, regards \o

**Comment by ghost** [comment]
Got it setup like I wanted to. Thanks again for keeping this fork alive.

Greetings
